version: '3'
services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - ./sql/data:/var/opt/mssql/data
      - ./sql/log:/var/opt/mssql/log
      - ./sql/secrets:/var/opt/mssql/secrets
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
  flag-service-api:
    depends_on:
      - sqlserver
      - unit-tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app