version: '3'
services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - ./sql/data:/var/opt/mssql/data
      - ./sql/log:/var/opt/mssql/log
      - ./sql/secrets:/var/opt/mssql/secrets
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
  flag-service-api:
    depends_on:
      - sqlserver
      - unit-tests
    build:
      context: .
      dockerfile: Dockerfile.dapr.dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
    # this is for testing only, sub with your env vars ${} for production
      - Database__Server=host.docker.internal
      - Database__Port=1433
      - Database__Username=sa
      - Database__Password=Password1
      - Database__Name=FlagServiceDB
      - RabbitMQ__HostName=host.docker.internal
      - RabbitMQ__UserName=RabbitMQ_user
      - RabbitMQ__Password=RabbitMQ_pass
      - Dapr_Mq_QueueName=flagpubsub