name: Docker Image CI (Dev)

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Build and run tests
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.test

  docker:
    needs: test
    runs-on: ubuntu-latest
    environment: public

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.dapr.dev
          push: true
          tags: ${{ secrets.DOCKER_USER }}/flag-service-dev:latest,${{ secrets.DOCKER_USER }}/flag-service-dev:${{ github.sha }}
