name: Docker Image CI (Dev)

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  login:
    runs-on: ubuntu-latest
    environment: public
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build:
    runs-on: ubuntu-latest
    needs: login
    environment: public
    steps:
      - uses: actions/build-push-action@v2
      - name: Build and push the Docker image
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_USER }}/flag-service-dev:latest
